name: Linux

on:
  push:
    paths:
    - '.github/workflows/**'
    - 'JuceLibraryCode/**'
    - 'PluginGenerator/**'
    - 'Plugins/**'
    - 'Resources/**'
    - 'Source/**'
    - 'CMakeLists.txt'
    - 'HelperFunctions.cmake'

jobs:
  build-ubuntu:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        sudo apt update
        cd Resources/Scripts
        sudo ./install_linux_dependencies.sh
        cd ../../Build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
        make -j4
#    - name: test
#      run: cd build && ctest
    - name: deploy_dev
      if: github.ref == 'refs/heads/development'
      env:
        ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      run: |
        cd Build
        cp -r Release open-ephys
        cp ../LICENSE open-ephys
        zipfile=open-ephys-latest-linux-dev.zip
        zip -r $zipfile open-ephys
        user_info="X-JFrog-Art-Api:$ARTIFACTORY_ACCESS_TOKEN"
        curl -H $user_info -T $zipfile "https://openephys.jfrog.io/artifactory/GUI-binaries/Dev/linux/$zipfile"
        cd ../Resources/Installers/Linux/Open-Ephys_Installer
        mkdir -p usr/local/bin/open-ephys-gui
        cp -r ../../../../Build/Release/* usr/local/bin/open-ephys-gui
        cp ../../../Scripts/40-open-ephys.rules usr/local/bin/open-ephys-gui
        cd ..
        dpkg-deb --build Open-Ephys_Installer
        installer=open-ephys-gui-latest-dev.deb
        mv -v Open-Ephys_Installer.deb $installer
        curl -H $user_info -T $installer "https://openephys.jfrog.io/artifactory/GUI-binaries/Dev-Installer/linux/$installer"
      shell: bash
    - name: deploy_test
      if: github.ref == 'refs/heads/testing'
      env:
        ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      run: |
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))
        cd Build
        cp -r Release open-ephys
        cp ../LICENSE open-ephys
        zipfile=open-ephys-${gui_ver}-linux-beta.zip
        zip -r $zipfile open-ephys
        user_info="X-JFrog-Art-Api:$ARTIFACTORY_ACCESS_TOKEN"
        curl -H $user_info -T $zipfile "https://openephys.jfrog.io/artifactory/GUI-binaries/Test/linux/$zipfile"
        cd ../Resources/Installers/Linux/Open-Ephys_Installer
        mkdir -p usr/local/bin/open-ephys-gui
        cp -r ../../../../Build/Release/* usr/local/bin/open-ephys-gui
        cp ../../../Scripts/40-open-ephys.rules usr/local/bin/open-ephys-gui
        cd ..
        dpkg-deb --build Open-Ephys_Installer
        installer=open-ephys-gui-${gui_ver}-beta.deb
        mv -v Open-Ephys_Installer.deb $installer
        curl -H $user_info -T $installer "https://openephys.jfrog.io/artifactory/GUI-binaries/Test-Installer/linux/$installer"
      shell: bash
    - name: deploy_release
      if: github.ref == 'refs/heads/main'
      env:
        ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      run: |
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))
        cd Build
        cp -r Release open-ephys
        cp ../LICENSE open-ephys
        zipfile=open-ephys-${gui_ver}-linux.zip
        zip -r $zipfile open-ephys
        user_info="X-JFrog-Art-Api:$ARTIFACTORY_ACCESS_TOKEN"
        curl -H $user_info -T $zipfile "https://openephys.jfrog.io/artifactory/GUI-binaries/Release/linux/$zipfile"
        cd ../Resources/Installers/Linux/Open-Ephys_Installer
        mkdir -p usr/local/bin/open-ephys-gui
        cp -r ../../../../Build/Release/* usr/local/bin/open-ephys-gui
        cp ../../../Scripts/40-open-ephys.rules usr/local/bin/open-ephys-gui
        cd ..
        dpkg-deb --build Open-Ephys_Installer
        installer=open-ephys-gui-${gui_ver}.deb
        mv Open-Ephys_Installer.deb $installer
        curl -H $user_info -T $installer "https://openephys.jfrog.io/artifactory/GUI-binaries/Release-Installer/linux/$installer"
      shell: bash
