name: Linux

on:
  push:
    paths:
    - '.github/workflows/**'
    - 'JuceLibraryCode/**'
    - 'PluginGenerator/**'
    - 'Plugins/**'
    - 'Resources/**'
    - 'Source/**'
    - 'CMakeLists.txt'
    - 'HelperFunctions.cmake'

jobs:
  build-ubuntu:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      env:
        CC: gcc-10
        CXX: g++-10
      run: |
        sudo apt update
        cd Resources/Scripts
        sudo ./install_linux_dependencies.sh
        cd ../../Build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
        make -j4
#    - name: test
#      run: cd build && ctest
    - name: deploy_dev
      if: github.ref == 'refs/heads/development-juce8'
      env:
        ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      run: |
        cd Build
        cp -r Release open-ephys
        cp ../LICENSE open-ephys
        zipfile=open-ephys-v1.0.0-dev-linux.zip
        zip -r $zipfile open-ephys
        user_info="X-JFrog-Art-Api:$ARTIFACTORY_ACCESS_TOKEN"
        curl -H $user_info -T $zipfile "https://openephys.jfrog.io/artifactory/GUI-binaries/1.0.0-dev/linux/$zipfile"
      shell: bash
    - name: deploy_preview
      if: github.ref == 'refs/heads/testing-juce8'
      env:
        ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      run: |
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))

        cd Build
        cp -r Release open-ephys
        cp ../LICENSE open-ephys
        zipfile=open-ephys-v1.0.0-alpha.1-linux.zip
        zip -r $zipfile open-ephys
        user_info="X-JFrog-Art-Api:$ARTIFACTORY_ACCESS_TOKEN"
        curl -H $user_info -T $zipfile "https://openephys.jfrog.io/artifactory/GUI-binaries/1.0.0-alpha/linux/$zipfile"

        cd ../Resources/Installers/Linux/Open-Ephys_Installer
        mkdir -p usr/local/bin/open-ephys-gui
        cp -r ../../../../Build/Release/* usr/local/bin/open-ephys-gui
        cp ../../../Scripts/40-open-ephys.rules usr/local/bin/open-ephys-gui
        cd ..
        dpkg-deb --build Open-Ephys_Installer
        installer=open-ephys-gui-v1.0.0-alpha.1.deb
        mv -v Open-Ephys_Installer.deb $installer
        curl -H $user_info -T $installer "https://openephys.jfrog.io/artifactory/GUI-binaries/1.0.0-alpha/linux/$installer"
      shell: bash
